// Japanese Verb Trainer — the verb dataset (split out of index.html).
// Loaded as a classic script before app.js; defines the global `VERBS`. See the
// top-of-file comment in app.js for the schema and the architecture map.

/* ============================================================================
   DATA — the 100-verb dataset
   ----------------------------------------------------------------------------
   Ordered by BCCWJ corpus frequency (rank 1 = most frequent). See file header
   for the full per-verb field schema and the する/言う #1 caveat.

   Editing notes:
     • rank must stay unique and contiguous 1..100 (the rank-range filter and
       the "#N" badge assume it).
     • tags drive BOTH semantic filters and the frequency-band Browse tags
       ("top1-25"…"top76-100"). If you re-rank, fix the band tags too.
     • mnem follows the MNEMONIC POLICY (sound-accurate first; see file header).
     • <ruby>漢字<rt>かな</rt></ruby> in examples renders furigana.
   To grow past 100, this array is the first thing to extract into verbs.json
   (see OUTSTANDING #7).
   ========================================================================== */
const VERBS=[
{rank:1,jp:"する",read:"する",mean:"to do",type:"irregular",jlpt:"N5",trans:"t",tags:["suru","top1-25"],
 mnem:'する → "soo-roo." Sounds like "<b>sue</b>-roo" — you take action, you <b>sue</b>. (or just: the all-purpose "do" verb)',tip:"Turns nouns into verbs: 勉強する. One of only 2 irregulars. #1 by raw token frequency (counting all 〜する compounds); near-tie with 言う.",ex:[["宿題を<ruby>する</ruby>。","Do homework."]]},
{rank:2,jp:"言う",read:"いう",mean:"to say",type:"godan",jlpt:"N5",trans:"t",tags:["speaking","communication","top1-25"],
 mnem:'いう = vowels "ee-oo." <b>I</b> say to <b>you</b> (i+u).',tip:"Content of speech, vs 話す = act of speaking. Ranks #1 in some BCCWJ counts that split 〜する compounds out — near-tie with する.",ex:[["彼は「行く」と<ruby>言<rt>い</rt></ruby>った。","He said \"I'll go.\""]]},
{rank:3,jp:"ある",read:"ある",mean:"to be / exist (inanimate)",type:"godan",jlpt:"N5",trans:"i",tags:["existence","top1-25"],
 mnem:'ある → "<b>are</b>" (as in "there <b>are</b> things").',tip:"Inanimate/abstract existence + possession. Irregular negative: ない.",ex:[["机の上に本が<ruby>ある</ruby>。","There's a book on the desk."]]},
{rank:4,jp:"なる",read:"なる",mean:"to become",type:"godan",jlpt:"N5",trans:"i",tags:["change","top1-25"],
 mnem:'なる → "<b>nah-ru</b>." Things turn into a "<b>new</b>-ru" state.',tip:"Adj+く+なる / Noun+に+なる. 医者になる.",ex:[["寒く<ruby>なる</ruby>。","It's getting cold."]]},
{rank:5,jp:"思う",read:"おもう",mean:"to think / feel",type:"godan",jlpt:"N5",trans:"t",tags:["emotion","cognition","top1-25"],
 mnem:'おもう → "oh-moh-oo." It weighs on you — "<b>omo</b>i" (重い heavy) thoughts.',tip:"Opinion/feeling. と思う quotes a thought. vs 考える = reason it out.",ex:[["いいと<ruby>思<rt>おも</rt></ruby>う。","I think it's good."]]},
{rank:6,jp:"行く",read:"いく",mean:"to go",type:"godan",jlpt:"N5",trans:"i",tags:["motion","top1-25"],
 mnem:'いく → "ee-koo." "<b>I</b>\'m off" — i-.',tip:"Irregular て-form 行って, not 行いて.",ex:[["映画を見に<ruby>行<rt>い</rt></ruby>く。","Going to watch a movie."]]},
{rank:7,jp:"来る",read:"くる",mean:"to come",type:"irregular",jlpt:"N5",trans:"i",tags:["motion","top1-25"],
 mnem:'くる → "koo-roo." A pigeon <b>coo</b>s as it <b>comes</b>.',tip:"Irregular: 来(き)ます/来(こ)ない/来(き)て.",ex:[["友達が<ruby>来<rt>く</rt></ruby>る。","A friend is coming."]]},
{rank:8,jp:"見る",read:"みる",mean:"to see / watch",type:"ichidan",jlpt:"N5",trans:"t",tags:["perception","top1-25"],
 mnem:'みる: <b>mi</b>~目(eye); "mee"r→mirror→look.',tip:"見る=look · 見える=visible · 見せる=show.",ex:[["映画を<ruby>見<rt>み</rt></ruby>る。","Watch a movie."]]},
{rank:9,jp:"やる",read:"やる",mean:"to do / give (casual)",type:"godan",jlpt:"N4",trans:"t",tags:["suru","giving","top1-25"],
 mnem:'やる → "<b>yah</b>-ru." Casual "<b>yeah</b>, I\'ll do it."',tip:"Casual する; also 'give' to inferiors/animals/plants.",ex:[["宿題を<ruby>やる</ruby>。","Do the homework."]]},
{rank:10,jp:"いる",read:"いる",mean:"to be / exist (animate)",type:"ichidan",jlpt:"N5",trans:"i",tags:["existence","top1-25"],
 mnem:'いる → "ee-ru." A living thing "<b>is</b>" here.',tip:"Animate existence. Also makes ~ている progressive.",ex:[["猫が<ruby>いる</ruby>。","There's a cat."]]},
{rank:11,jp:"できる",read:"できる",mean:"to be able / be done",type:"ichidan",jlpt:"N5",trans:"i",tags:["ability","top1-25"],
 mnem:'できる → "deh-kee-ru." Sounds like "<b>the key</b>-ru" — having the key means you <b>can</b> do it.',tip:"Potential of する. ことができる = able to.",ex:[["日本語が<ruby>できる</ruby>。","I can speak Japanese."]]},
{rank:12,jp:"持つ",read:"もつ",mean:"to hold / carry / have",type:"godan",jlpt:"N5",trans:"t",tags:["top1-25"],
 mnem:'もつ → "moh-tsu," a "<b>lot</b>" to hold.',tip:"One vowel from 待つ(まつ wait).",ex:[["かばんを<ruby>持<rt>も</rt></ruby>つ。","Carry a bag."]]},
{rank:13,jp:"出る",read:"でる",mean:"to exit / leave / come out",type:"ichidan",jlpt:"N5",trans:"i",tags:["motion","ti-pair","top1-25"],
 mnem:'でる → "deh-ru" = "<b>door</b>-u," out the door.',tip:"Intransitive. Pair 出す(だす, take out).",ex:[["家を<ruby>出<rt>で</rt></ruby>る。","Leave the house."]]},
{rank:14,jp:"考える",read:"かんがえる",mean:"to think / consider",type:"ichidan",jlpt:"N4",trans:"t",tags:["cognition","top1-25"],
 mnem:'かんがえる: "<b>kangaroo</b>" pondering hard.',tip:"Reasoning/deliberation, vs 思う = feel/opinion.",ex:[["将来を<ruby>考<rt>かんが</rt></ruby>える。","Think about the future."]]},
{rank:15,jp:"入る",read:"はいる",mean:"to enter",type:"godan",jlpt:"N5",trans:"i",tags:["motion","fake","ti-pair","top1-25"],
 mnem:'はいる → "hai-ru." Say "<b>hi!</b>" as you enter.',tip:"FAKE-ICHIDAN: -iru but godan. 入って. Pair 入れる(いれる, put in).",ex:[["部屋に<ruby>入<rt>はい</rt></ruby>る。","Enter the room."]]},
{rank:16,jp:"使う",read:"つかう",mean:"to use",type:"godan",jlpt:"N5",trans:"t",tags:["top1-25"],
 mnem:'つかう → "tsoo-kah-oo." You "<b>took</b>" a tool to <b>use</b>.',tip:"使って = using/by means of.",ex:[["はしを<ruby>使<rt>つか</rt></ruby>う。","Use chopsticks."]]},
{rank:17,jp:"知る",read:"しる",mean:"to know / find out",type:"godan",jlpt:"N5",trans:"t",tags:["cognition","fake","top1-25"],
 mnem:'しる → "shee-ru." A "<b>shrew</b>"d person <b>knows</b>.',tip:"FAKE-ICHIDAN: -iru, godan. 知って. 知っている=know (state).",ex:[["彼を<ruby>知<rt>し</rt></ruby>っている。","I know him."]]},
{rank:18,jp:"分かる",read:"わかる",mean:"to understand",type:"godan",jlpt:"N5",trans:"i",tags:["cognition","top1-25"],
 mnem:'わかる → "wah-kah-ru." "<b>What</b>? — oh, I get it."',tip:"Takes が, not を: 意味が分かる. Intransitive 'becomes clear.'",ex:[["意味が<ruby>分<rt>わ</rt></ruby>かる。","I understand the meaning."]]},
{rank:19,jp:"取る",read:"とる",mean:"to take / grab",type:"godan",jlpt:"N5",trans:"t",tags:["top1-25"],
 mnem:'とる → "<b>toe</b>-ru." You reach and <b>take</b> it.',tip:"Broad 'take/grab/pick up.' 写真を撮る (photo) is same reading.",ex:[["塩を<ruby>取<rt>と</rt></ruby>る。","Pass/take the salt."]]},
{rank:20,jp:"話す",read:"はなす",mean:"to speak / talk",type:"godan",jlpt:"N5",trans:"t",tags:["speaking","communication","top1-25"],
 mnem:'はなす: 鼻(はな nose) — talk near your hana.',tip:"と話す=with (mutual) · に話す=to (one-way).",ex:[["友達と<ruby>話<rt>はな</rt></ruby>す。","Talk with a friend."]]},
{rank:21,jp:"聞く",read:"きく",mean:"to listen / ask / hear",type:"godan",jlpt:"N5",trans:"t",tags:["speaking","communication","perception","top1-25"],
 mnem:'きく → "kee-koo." "<b>Keek</b>—what was that?" listen, then ask.',tip:"Both 'listen' and 'ask.' 聞こえる=can hear.",ex:[["音楽を<ruby>聞<rt>き</rt></ruby>く。","Listen to music."]]},
{rank:22,jp:"作る",read:"つくる",mean:"to make",type:"godan",jlpt:"N5",trans:"t",tags:["food","top1-25"],
 mnem:'つくる → "to cook-ru," you make it.',tip:"作って. 料理を作る.",ex:[["料理を<ruby>作<rt>つく</rt></ruby>る。","Make a meal."]]},
{rank:23,jp:"始める",read:"はじめる",mean:"to begin (something)",type:"ichidan",jlpt:"N4",trans:"t",tags:["change","ti-pair","top1-25"],
 mnem:'はじめる: like "<b>hajimemashite</b>" — a beginning.',tip:"Transitive. Pair 始まる(はじまる, it begins).",ex:[["仕事を<ruby>始<rt>はじ</rt></ruby>める。","Start work."]]},
{rank:24,jp:"待つ",read:"まつ",mean:"to wait",type:"godan",jlpt:"N5",trans:"t",tags:["top1-25"],
 mnem:'まつ = 松(pine). A pine stands and waits.',tip:"を particle. One vowel from 持つ(もつ).",ex:[["ここで<ruby>待<rt>ま</rt></ruby>つ。","Wait here."]]},
{rank:25,jp:"使える",read:"つかえる",mean:"to be usable",type:"ichidan",jlpt:"N4",trans:"i",tags:["ability","top1-25"],
 mnem:'Potential of 使う — "tsoo-kah-eru," can be used.',tip:"Potential form of 使う.",ex:[["これは<ruby>使<rt>つか</rt></ruby>える。","This is usable."]]},
{rank:26,jp:"書く",read:"かく",mean:"to write",type:"godan",jlpt:"N5",trans:"t",tags:["communication","work","top26-50"],
 mnem:'かく → "kah-koo." You "<b>cook</b>" up words on paper.',tip:"描く(draw) is same reading. 書いて.",ex:[["手紙を<ruby>書<rt>か</rt></ruby>く。","Write a letter."]]},
{rank:27,jp:"読む",read:"よむ",mean:"to read",type:"godan",jlpt:"N5",trans:"t",tags:["communication","top26-50"],
 mnem:'よむ → "yo-mu." "<b>Yo</b>, mu"-se over a book.',tip:"Confusable with 呼ぶ(よぶ call).",ex:[["本を<ruby>読<rt>よ</rt></ruby>む。","Read a book."]]},
{rank:28,jp:"買う",read:"かう",mean:"to buy",type:"godan",jlpt:"N5",trans:"t",tags:["money","top26-50"],
 mnem:'かう = "cow." Buy a cow at market.',tip:"Homophone 飼う(keep a pet).",ex:[["服を<ruby>買<rt>か</rt></ruby>う。","Buy clothes."]]},
{rank:29,jp:"食べる",read:"たべる",mean:"to eat",type:"ichidan",jlpt:"N5",trans:"t",tags:["food","top26-50"],
 mnem:'たべる: sit at the "<b>table</b>" (tabe) to eat.',tip:"Model ichidan.",ex:[["朝ご飯を<ruby>食<rt>た</rt></ruby>べる。","Eat breakfast."]]},
{rank:30,jp:"飲む",read:"のむ",mean:"to drink",type:"godan",jlpt:"N5",trans:"t",tags:["food","body","top26-50"],
 mnem:'のむ = "nom," the drinking sound.',tip:"Also take medicine: 薬を飲む.",ex:[["水を<ruby>飲<rt>の</rt></ruby>む。","Drink water."]]},
{rank:31,jp:"立つ",read:"たつ",mean:"to stand",type:"godan",jlpt:"N5",trans:"i",tags:["body","ti-pair","top26-50"],
 mnem:'たつ → "tah-tsu." You "<b>tower</b>" up to stand.',tip:"Intransitive. Pair 立てる(たてる, stand sth up/build).",ex:[["駅の前に<ruby>立<rt>た</rt></ruby>つ。","Stand in front of the station."]]},
{rank:32,jp:"座る",read:"すわる",mean:"to sit",type:"godan",jlpt:"N5",trans:"i",tags:["body","top26-50"],
 mnem:'すわる → "soo-wah-ru." You "<b>swirl</b>" down to sit.',tip:"に座る on a seat.",ex:[["いすに<ruby>座<rt>すわ</rt></ruby>る。","Sit on the chair."]]},
{rank:33,jp:"歩く",read:"あるく",mean:"to walk",type:"godan",jlpt:"N5",trans:"i",tags:["motion","body","top26-50"],
 mnem:'あるく: "<b>are</b> we there yet?" as you walk.',tip:"Path takes を.",ex:[["公園を<ruby>歩<rt>ある</rt></ruby>く。","Walk in the park."]]},
{rank:34,jp:"走る",read:"はしる",mean:"to run",type:"godan",jlpt:"N5",trans:"i",tags:["motion","body","fake","top26-50"],
 mnem:'はしる = "hustle" — you hustle to run.',tip:"FAKE-ICHIDAN: -iru, godan. 走って.",ex:[["駅まで<ruby>走<rt>はし</rt></ruby>る。","Run to the station."]]},
{rank:35,jp:"乗る",read:"のる",mean:"to ride / board",type:"godan",jlpt:"N5",trans:"i",tags:["transit","top26-50"],
 mnem:'のる → "no-ru." "<b>No</b> room!" but you ride.',tip:"に particle: 電車に乗る.",ex:[["バスに<ruby>乗<rt>の</rt></ruby>る。","Ride the bus."]]},
{rank:36,jp:"降りる",read:"おりる",mean:"to get off / descend",type:"ichidan",jlpt:"N4",trans:"i",tags:["transit","motion","top26-50"],
 mnem:'おりる → "oh-ree-ru." "<b>Oh</b>, my stop!"',tip:"を/から. Homophone 下りる(go down).",ex:[["次の駅で<ruby>降<rt>お</rt></ruby>りる。","Get off at the next stop."]]},
{rank:37,jp:"帰る",read:"かえる",mean:"to return home",type:"godan",jlpt:"N5",trans:"i",tags:["motion","daily","fake","top26-50"],
 mnem:'かえる = 蛙(frog). A frog hops home.',tip:"FAKE-ICHIDAN: -eru, godan. 帰って.",ex:[["家に<ruby>帰<rt>かえ</rt></ruby>る。","Go home."]]},
{rank:38,jp:"会う",read:"あう",mean:"to meet",type:"godan",jlpt:"N5",trans:"i",tags:["speaking","communication","top26-50"],
 mnem:'あう → "ow!" you bump into & meet someone.',tip:"に particle. Homophone 合う(fit).",ex:[["駅で<ruby>会<rt>あ</rt></ruby>う。","Meet at the station."]]},
{rank:39,jp:"買える",read:"かえる",mean:"to be able to buy",type:"ichidan",jlpt:"N4",trans:"i",tags:["money","ability","top26-50"],
 mnem:'Potential of 買う — "can cow," can buy.',tip:"Homophone cluster: 帰る/変える/蛙.",ex:[["安く<ruby>買<rt>か</rt></ruby>える。","Can buy it cheaply."]]},
{rank:40,jp:"出す",read:"だす",mean:"to take out / submit",type:"godan",jlpt:"N5",trans:"t",tags:["ti-pair","work","top26-50"],
 mnem:'だす → "dah-su." You "<b>thrust</b>" it out.',tip:"Transitive pair of 出る. 手紙を出す=mail a letter.",ex:[["ごみを<ruby>出<rt>だ</rt></ruby>す。","Take out the trash."]]},
{rank:41,jp:"入れる",read:"いれる",mean:"to put in / insert",type:"ichidan",jlpt:"N5",trans:"t",tags:["ti-pair","top26-50"],
 mnem:'いれる → "ee-reh-ru." You "<b>ear</b>"-mark a slot to insert.',tip:"Transitive pair of 入る. コーヒーを入れる=make coffee.",ex:[["かばんに<ruby>入<rt>い</rt></ruby>れる。","Put it in the bag."]]},
{rank:42,jp:"始まる",read:"はじまる",mean:"to begin (intrans.)",type:"godan",jlpt:"N4",trans:"i",tags:["change","ti-pair","top26-50"],
 mnem:'Intransitive twin of 始める — it begins on its own.',tip:"Pair 始める. 映画が始まる.",ex:[["授業が<ruby>始<rt>はじ</rt></ruby>まる。","Class begins."]]},
{rank:43,jp:"終わる",read:"おわる",mean:"to end / finish",type:"godan",jlpt:"N5",trans:"i",tags:["change","ti-pair","top26-50"],
 mnem:'おわる → "oh-wah-ru." "<b>Oh</b>, war\'s" over.',tip:"Mostly intransitive. Pair 終える(おえる, finish sth).",ex:[["仕事が<ruby>終<rt>お</rt></ruby>わる。","Work ends."]]},
{rank:44,jp:"働く",read:"はたらく",mean:"to work",type:"godan",jlpt:"N5",trans:"i",tags:["work","top26-50"],
 mnem:'はたらく: "<b>hot</b> a-<b>luck</b>"—hard work, hot & lucky.',tip:"で marks workplace: 会社で働く.",ex:[["銀行で<ruby>働<rt>はたら</rt></ruby>く。","Work at a bank."]]},
{rank:45,jp:"住む",read:"すむ",mean:"to live / reside",type:"godan",jlpt:"N5",trans:"i",tags:["daily","top26-50"],
 mnem:'すむ → "soo-mu." You "<b>assume</b>" residence.',tip:"に住む + ~ている: 東京に住んでいる.",ex:[["東京に<ruby>住<rt>す</rt></ruby>む。","Live in Tokyo."]]},
{rank:46,jp:"持っていく",read:"もっていく",mean:"to take (something along)",type:"godan",jlpt:"N4",trans:"t",tags:["motion","top26-50"],
 mnem:'持つ + 行く — hold it and go.',tip:"Carry sth away from here. Contrast 持ってくる.",ex:[["傘を<ruby>持<rt>も</rt></ruby>っていく。","Take an umbrella along."]]},
{rank:47,jp:"待てる",read:"まてる",mean:"to be able to wait",type:"ichidan",jlpt:"N4",trans:"i",tags:["ability","top26-50"],
 mnem:'Potential of 待つ — can wait.',tip:"Potential of 待つ.",ex:[["まだ<ruby>待<rt>ま</rt></ruby>てる。","I can still wait."]]},
{rank:48,jp:"見せる",read:"みせる",mean:"to show",type:"ichidan",jlpt:"N4",trans:"t",tags:["perception","communication","top26-50"],
 mnem:'みせる: a "<b>mise</b>"-en-scène you show off.',tip:"Causative-ish of 見る: make someone see.",ex:[["写真を<ruby>見<rt>み</rt></ruby>せる。","Show a photo."]]},
{rank:49,jp:"覚える",read:"おぼえる",mean:"to memorize / remember",type:"ichidan",jlpt:"N4",trans:"t",tags:["cognition","work","top26-50"],
 mnem:'おぼえる: "oh, <b>boy</b>, eru"—learn it by heart.',tip:"Commit to memory. vs 思い出す=recall.",ex:[["単語を<ruby>覚<rt>おぼ</rt></ruby>える。","Memorize vocabulary."]]},
{rank:50,jp:"忘れる",read:"わすれる",mean:"to forget",type:"ichidan",jlpt:"N5",trans:"t",tags:["cognition","top26-50"],
 mnem:'わすれる: "<b>was</b>-reru"—it <b>was</b> there, now forgotten.',tip:"忘れ物=forgotten item.",ex:[["名前を<ruby>忘<rt>わす</rt></ruby>れる。","Forget a name."]]},
{rank:51,jp:"開ける",read:"あける",mean:"to open (something)",type:"ichidan",jlpt:"N5",trans:"t",tags:["ti-pair","top51-75"],
 mnem:'あける: dawn "breaks" (明ける), you open up.',tip:"Transitive. Pair 開く(あく).",ex:[["窓を<ruby>開<rt>あ</rt></ruby>ける。","Open the window."]]},
{rank:52,jp:"閉める",read:"しめる",mean:"to close (something)",type:"ichidan",jlpt:"N5",trans:"t",tags:["ti-pair","top51-75"],
 mnem:'しめる: "<b>shh</b>-me"—shut it to be quiet.',tip:"Transitive. Pair 閉まる. Same reading as 締める(fasten).",ex:[["ドアを<ruby>閉<rt>し</rt></ruby>める。","Close the door."]]},
{rank:53,jp:"開く",read:"あく",mean:"to open (intrans.)",type:"godan",jlpt:"N4",trans:"i",tags:["ti-pair","top51-75"],
 mnem:'あく → "ah-koo." It pops "<b>a-gap</b>" open.',tip:"Intransitive. Pair 開ける. ドアが開く.",ex:[["ドアが<ruby>開<rt>あ</rt></ruby>く。","The door opens."]]},
{rank:54,jp:"閉まる",read:"しまる",mean:"to close (intrans.)",type:"godan",jlpt:"N4",trans:"i",tags:["ti-pair","top51-75"],
 mnem:'しまる: it "<b>shimmers</b>" shut by itself.',tip:"Intransitive. Pair 閉める.",ex:[["店が<ruby>閉<rt>し</rt></ruby>まる。","The shop closes."]]},
{rank:55,jp:"つける",read:"つける",mean:"to turn on / attach",type:"ichidan",jlpt:"N4",trans:"t",tags:["onoff","wearing","ti-pair","top51-75"],
 mnem:'つける = "stick-eru"—stick the power on.',tip:"Transitive. Pair つく. Also wear mask/watch.",ex:[["電気を<ruby>付<rt>つ</rt></ruby>ける。","Turn on the light."]]},
{rank:56,jp:"消す",read:"けす",mean:"to turn off / erase",type:"godan",jlpt:"N4",trans:"t",tags:["onoff","ti-pair","top51-75"],
 mnem:'けす = "case closed"—kill the power.',tip:"Transitive. Pair 消える(きえる).",ex:[["電気を<ruby>消<rt>け</rt></ruby>す。","Turn off the light."]]},
{rank:57,jp:"つく",read:"つく",mean:"to come on / be attached",type:"godan",jlpt:"N4",trans:"i",tags:["onoff","ti-pair","top51-75"],
 mnem:'つく → "tsoo-koo." It "<b>took</b>"—power\'s on.',tip:"Intransitive. Pair つける.",ex:[["電気が<ruby>付<rt>つ</rt></ruby>く。","The light comes on."]]},
{rank:58,jp:"消える",read:"きえる",mean:"to go out / disappear",type:"ichidan",jlpt:"N4",trans:"i",tags:["onoff","ti-pair","top51-75"],
 mnem:'きえる: "<b>key</b>-eru"—it vanishes like a magic key.',tip:"Intransitive. Pair 消す.",ex:[["電気が<ruby>消<rt>き</rt></ruby>える。","The light goes out."]]},
{rank:59,jp:"着る",read:"きる",mean:"to wear (torso)",type:"ichidan",jlpt:"N5",trans:"t",tags:["wearing","daily","top51-75"],
 mnem:'きる: a "<b>key</b>" on a lanyard on your chest.',tip:"Torso: shirts, jackets, suits.",ex:[["スーツを<ruby>着<rt>き</rt></ruby>る。","Wear a suit."]]},
{rank:60,jp:"履く",read:"はく",mean:"to wear (legs/feet)",type:"godan",jlpt:"N5",trans:"t",tags:["wearing","daily","top51-75"],
 mnem:'はく = "hike"—boots & trousers, lower body.',tip:"Pants, skirts, shoes, socks.",ex:[["靴を<ruby>履<rt>は</rt></ruby>く。","Wear shoes."]]},
{rank:61,jp:"かぶる",read:"かぶる",mean:"to wear (head)",type:"godan",jlpt:"N4",trans:"t",tags:["wearing","top51-75"],
 mnem:'かぶる ≈ "cover" (cab-ur)—cover the head.',tip:"Hats, caps, helmets.",ex:[["帽子を<ruby>被<rt>かぶ</rt></ruby>る。","Wear a hat."]]},
{rank:62,jp:"締める",read:"しめる",mean:"to fasten (tie/belt)",type:"ichidan",jlpt:"N3",trans:"t",tags:["wearing","ti-pair","top51-75"],
 mnem:'しめる: "shimmy" it tight.',tip:"Same reading as 閉める(close).",ex:[["ネクタイを<ruby>締<rt>し</rt></ruby>める。","Fasten a tie."]]},
{rank:63,jp:"かける",read:"かける",mean:"to wear (glasses)/call/hang",type:"ichidan",jlpt:"N4",trans:"t",tags:["wearing","communication","top51-75"],
 mnem:'かける: "cackle" while hanging glasses or a call.',tip:"眼鏡をかける · 電話をかける.",ex:[["眼鏡を<ruby>掛<rt>か</rt></ruby>ける。","Wear glasses."]]},
{rank:64,jp:"呼ぶ",read:"よぶ",mean:"to call / summon",type:"godan",jlpt:"N4",trans:"t",tags:["speaking","communication","transit","top51-75"],
 mnem:'よぶ: shout "<b>Yo!</b>" to call someone.',tip:"Summon. Phone = 電話をかける. Confusable 読む.",ex:[["タクシーを<ruby>呼<rt>よ</rt></ruby>ぶ。","Call a taxi."]]},
{rank:65,jp:"起きる",read:"おきる",mean:"to wake / get up / occur",type:"ichidan",jlpt:"N5",trans:"i",tags:["daily","body","top51-75"],
 mnem:'おきる: "<b>oh, key</b>-ru"—alarm, get up.',tip:"Confusable 起こる(occur)/怒る(angry).",ex:[["七時に<ruby>起<rt>お</rt></ruby>きる。","Wake up at 7."]]},
{rank:66,jp:"寝る",read:"ねる",mean:"to sleep / go to bed",type:"ichidan",jlpt:"N5",trans:"i",tags:["daily","body","top51-75"],
 mnem:'ねる: curl in the "<b>nest</b>" to sleep.',tip:"寝る=go to bed · 眠る=be asleep.",ex:[["早く<ruby>寝<rt>ね</rt></ruby>る。","Go to bed early."]]},
{rank:67,jp:"起こす",read:"おこす",mean:"to wake (someone) / cause",type:"godan",jlpt:"N4",trans:"t",tags:["daily","ti-pair","top51-75"],
 mnem:'おこす: you "<b>oh-cause</b>" someone to wake.',tip:"Transitive pair of 起きる.",ex:[["子供を<ruby>起<rt>お</rt></ruby>こす。","Wake the child."]]},
{rank:68,jp:"あげる",read:"あげる",mean:"to give (to others)",type:"ichidan",jlpt:"N5",trans:"t",tags:["giving","top51-75"],
 mnem:'あげる: you "<b>upgrade</b>" (a-ge) someone with a gift.',tip:"I/we → others. Outward direction.",ex:[["友達にプレゼントを<ruby>あげる</ruby>。","Give a friend a present."]]},
{rank:69,jp:"くれる",read:"くれる",mean:"to give (to me/us)",type:"ichidan",jlpt:"N5",trans:"t",tags:["giving","top51-75"],
 mnem:'くれる: someone is "<b>cool</b>-reru" enough to give me.',tip:"Others → me/my side. Inward direction.",ex:[["友達が本を<ruby>くれる</ruby>。","A friend gives me a book."]]},
{rank:70,jp:"もらう",read:"もらう",mean:"to receive",type:"godan",jlpt:"N5",trans:"t",tags:["giving","top51-75"],
 mnem:'もらう: "moh-rah-oo"—"<b>more</b> for me," I receive.',tip:"に/から marks giver. I get from someone.",ex:[["先生に本を<ruby>もらう</ruby>。","Receive a book from the teacher."]]},
{rank:71,jp:"勉強する",read:"べんきょうする",mean:"to study",type:"irregular",jlpt:"N5",trans:"t",tags:["suru","study","work","top51-75"],
 mnem:'勉強(benkyō effort)+する.',tip:"Classic suru-verb.",ex:[["日本語を<ruby>勉強<rt>べんきょう</rt></ruby>する。","Study Japanese."]]},
{rank:72,jp:"電話する",read:"でんわする",mean:"to phone",type:"irregular",jlpt:"N5",trans:"i",tags:["suru","communication","top51-75"],
 mnem:'電話(phone)+する.',tip:"= 電話をかける. に marks who you call.",ex:[["母に<ruby>電話<rt>でんわ</rt></ruby>する。","Phone my mother."]]},
{rank:73,jp:"運転する",read:"うんてんする",mean:"to drive",type:"irregular",jlpt:"N4",trans:"t",tags:["suru","transit","top51-75"],
 mnem:'運転(driving)+する.',tip:"を marks the vehicle: 車を運転する.",ex:[["車を<ruby>運転<rt>うんてん</rt></ruby>する。","Drive a car."]]},
{rank:74,jp:"練習する",read:"れんしゅうする",mean:"to practice",type:"irregular",jlpt:"N4",trans:"t",tags:["suru","study","top51-75"],
 mnem:'練習(practice)+する.',tip:"を marks what you practice.",ex:[["ピアノを<ruby>練習<rt>れんしゅう</rt></ruby>する。","Practice piano."]]},
{rank:75,jp:"説明する",read:"せつめいする",mean:"to explain",type:"irregular",jlpt:"N4",trans:"t",tags:["suru","communication","work","top51-75"],
 mnem:'説明(explanation)+する.',tip:"を marks what; に marks listener.",ex:[["理由を<ruby>説明<rt>せつめい</rt></ruby>する。","Explain the reason."]]},
{rank:76,jp:"洗う",read:"あらう",mean:"to wash",type:"godan",jlpt:"N5",trans:"t",tags:["daily","food","top76-100"],
 mnem:'あらう: "ah-<b>row</b>"—scrub in a row to wash.',tip:"手を洗う.",ex:[["手を<ruby>洗<rt>あら</rt></ruby>う。","Wash hands."]]},
{rank:77,jp:"切る",read:"きる",mean:"to cut",type:"godan",jlpt:"N5",trans:"t",tags:["food","fake","top76-100"],
 mnem:'きる: "<b>keel</b>"—slice it clean.',tip:"FAKE-ICHIDAN: -iru, godan! 切って. Same reading as 着る.",ex:[["野菜を<ruby>切<rt>き</rt></ruby>る。","Cut vegetables."]]},
{rank:78,jp:"料理する",read:"りょうりする",mean:"to cook",type:"irregular",jlpt:"N4",trans:"t",tags:["suru","food","top76-100"],
 mnem:'料理(cooking)+する.',tip:"Or just 作る for making a dish.",ex:[["夕飯を<ruby>料理<rt>りょうり</rt></ruby>する。","Cook dinner."]]},
{rank:79,jp:"払う",read:"はらう",mean:"to pay",type:"godan",jlpt:"N4",trans:"t",tags:["money","top76-100"],
 mnem:'はらう: "ha-<b>row</b>"—hand over the dough.',tip:"お金を払う. 支払う=formal pay.",ex:[["お金を<ruby>払<rt>はら</rt></ruby>う。","Pay money."]]},
{rank:80,jp:"売る",read:"うる",mean:"to sell",type:"godan",jlpt:"N4",trans:"t",tags:["money","ti-pair","top76-100"],
 mnem:'うる → "oo-ru." "You\'re-<b>ru</b>" selling it now.',tip:"Pair 売れる(sell well/be sold).",ex:[["車を<ruby>売<rt>う</rt></ruby>る。","Sell a car."]]},
{rank:81,jp:"貸す",read:"かす",mean:"to lend",type:"godan",jlpt:"N4",trans:"t",tags:["money","giving","top76-100"],
 mnem:'かす: "<b>cash</b>"—lend out cash.',tip:"に marks borrower. Opposite 借りる.",ex:[["お金を<ruby>貸<rt>か</rt></ruby>す。","Lend money."]]},
{rank:82,jp:"借りる",read:"かりる",mean:"to borrow",type:"ichidan",jlpt:"N4",trans:"t",tags:["money","top76-100"],
 mnem:'かりる: "<b>curry</b>-ru"—borrow some curry.',tip:"から/に marks lender. Opposite 貸す.",ex:[["本を<ruby>借<rt>か</rt></ruby>りる。","Borrow a book."]]},
{rank:83,jp:"送る",read:"おくる",mean:"to send / see off",type:"godan",jlpt:"N4",trans:"t",tags:["communication","top76-100"],
 mnem:'おくる: "oh-<b>koo</b>-ru"—you scoot it off.',tip:"メールを送る. Also escort someone.",ex:[["メールを<ruby>送<rt>おく</rt></ruby>る。","Send an email."]]},
{rank:84,jp:"教える",read:"おしえる",mean:"to teach / tell",type:"ichidan",jlpt:"N5",trans:"t",tags:["communication","study","top76-100"],
 mnem:'おしえる: "oh-<b>she</b>-eru"—she teaches.',tip:"に marks learner. Also 'inform.'",ex:[["日本語を<ruby>教<rt>おし</rt></ruby>える。","Teach Japanese."]]},
{rank:85,jp:"習う",read:"ならう",mean:"to learn (be taught)",type:"godan",jlpt:"N4",trans:"t",tags:["study","top76-100"],
 mnem:'ならう: "nah-<b>row</b>"—learn in a row of desks.',tip:"Learn from a teacher. vs 覚える=memorize.",ex:[["ピアノを<ruby>習<rt>なら</rt></ruby>う。","Learn piano."]]},
{rank:86,jp:"思い出す",read:"おもいだす",mean:"to recall",type:"godan",jlpt:"N4",trans:"t",tags:["cognition","top76-100"],
 mnem:'思う+出す—pull a thought back out.',tip:"Recall sth, vs 覚える=memorize.",ex:[["名前を<ruby>思<rt>おも</rt></ruby>い出す。","Recall a name."]]},
{rank:87,jp:"感じる",read:"かんじる",mean:"to feel",type:"ichidan",jlpt:"N3",trans:"t",tags:["emotion","body","top76-100"],
 mnem:'かんじる: "kan-<b>jee</b>-ru"—you can feel it.',tip:"Sense/emotion. 漢字(kanji) homophone of stem.",ex:[["寒さを<ruby>感<rt>かん</rt></ruby>じる。","Feel the cold."]]},
{rank:88,jp:"困る",read:"こまる",mean:"to be troubled",type:"godan",jlpt:"N4",trans:"i",tags:["emotion","top76-100"],
 mnem:'こまる: "<b>comma</b>-ru"—stuck mid-sentence, troubled.',tip:"困っている=in a fix.",ex:[["お金がなくて<ruby>困<rt>こま</rt></ruby>る。","Troubled with no money."]]},
{rank:89,jp:"泣く",read:"なく",mean:"to cry",type:"godan",jlpt:"N4",trans:"i",tags:["emotion","body","top76-100"],
 mnem:'なく: "<b>knock</b>"—tears knock loose.',tip:"鳴く(animal sound) same reading.",ex:[["子供が<ruby>泣<rt>な</rt></ruby>く。","The child cries."]]},
{rank:90,jp:"笑う",read:"わらう",mean:"to laugh / smile",type:"godan",jlpt:"N4",trans:"i",tags:["emotion","body","top76-100"],
 mnem:'わらう: "wah-<b>row</b>"—a row of laughs, ha-ha.',tip:"笑って=smiling.",ex:[["みんなで<ruby>笑<rt>わら</rt></ruby>う。","Everyone laughs."]]},
{rank:91,jp:"立てる",read:"たてる",mean:"to stand sth up / build",type:"ichidan",jlpt:"N4",trans:"t",tags:["ti-pair","top76-100"],
 mnem:'Transitive twin of 立つ — you erect it.',tip:"Pair 立つ. 計画を立てる=make a plan.",ex:[["計画を<ruby>立<rt>た</rt></ruby>てる。","Make a plan."]]},
{rank:92,jp:"変える",read:"かえる",mean:"to change (something)",type:"ichidan",jlpt:"N4",trans:"t",tags:["change","ti-pair","top76-100"],
 mnem:'かえる: a frog (蛙) "<b>changes</b>" from tadpole.',tip:"Transitive. Pair 変わる. Homophone 帰る/買える.",ex:[["予定を<ruby>変<rt>か</rt></ruby>える。","Change the schedule."]]},
{rank:93,jp:"変わる",read:"かわる",mean:"to change (intrans.)",type:"godan",jlpt:"N4",trans:"i",tags:["change","ti-pair","top76-100"],
 mnem:'かわる: "ka-<b>wah</b>-ru"—it shifts on its own.',tip:"Intransitive. Pair 変える.",ex:[["季節が<ruby>変<rt>か</rt></ruby>わる。","The seasons change."]]},
{rank:94,jp:"止まる",read:"とまる",mean:"to stop (intrans.)",type:"godan",jlpt:"N4",trans:"i",tags:["transit","ti-pair","top76-100"],
 mnem:'とまる: "<b>toe</b>-maru"—it halts at your toe.',tip:"Intransitive. Pair 止める(とめる).",ex:[["電車が<ruby>止<rt>と</rt></ruby>まる。","The train stops."]]},
{rank:95,jp:"止める",read:"とめる",mean:"to stop / park (trans.)",type:"ichidan",jlpt:"N4",trans:"t",tags:["transit","ti-pair","top76-100"],
 mnem:'Transitive twin of 止まる — you bring it to a halt.',tip:"Pair 止まる. 車を止める=park.",ex:[["車を<ruby>止<rt>と</rt></ruby>める。","Park the car."]]},
{rank:96,jp:"探す",read:"さがす",mean:"to search for",type:"godan",jlpt:"N4",trans:"t",tags:["daily","top76-100"],
 mnem:'さがす: "sah-<b>gus</b>"—you dig (sagu) to find it.',tip:"を marks what you seek.",ex:[["鍵を<ruby>探<rt>さが</rt></ruby>す。","Search for keys."]]},
{rank:97,jp:"見つける",read:"みつける",mean:"to find",type:"ichidan",jlpt:"N4",trans:"t",tags:["daily","perception","ti-pair","top76-100"],
 mnem:'見る+つける—spot it and lock on.',tip:"Transitive. Pair 見つかる(be found).",ex:[["答えを<ruby>見<rt>み</rt></ruby>つける。","Find the answer."]]},
{rank:98,jp:"持ってくる",read:"もってくる",mean:"to bring (something here)",type:"irregular",jlpt:"N4",trans:"t",tags:["motion","top76-100"],
 mnem:'持つ + 来る — hold it and come.',tip:"Toward here. Contrast 持っていく.",ex:[["お茶を<ruby>持<rt>も</rt></ruby>ってくる。","Bring some tea."]]},
{rank:99,jp:"連れていく",read:"つれていく",mean:"to take (a person) along",type:"godan",jlpt:"N4",trans:"t",tags:["motion","top76-100"],
 mnem:'連れる(accompany)+行く — take a person away.',tip:"For people/animals. 物 uses 持っていく.",ex:[["子供を<ruby>連<rt>つ</rt></ruby>れていく。","Take the child along."]]},
{rank:100,jp:"手伝う",read:"てつだう",mean:"to help / assist",type:"godan",jlpt:"N4",trans:"t",tags:["work","communication","top76-100"],
 mnem:'てつだう: "<b>te</b>(hand)-tsudau"—lend a hand.',tip:"を marks task/person helped.",ex:[["仕事を<ruby>手伝<rt>てつだ</rt></ruby>う。","Help with work."]]}
];
